# Generated by Django 4.1.1 on 2022-10-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typeonline', models.BooleanField(blank=True, null=True)),
                ('typefysical', models.BooleanField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startdatetime', '-enddatetime'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
