# Generated by Django 4.1.1 on 2022-10-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='descr',
        ),
    ]
